### ISSUE TITLE
[Leanplum syncResourcesAsync:YES] - Causes UI to freeze

### ISSUE THREAD

**Issue by NitWitStudios** [Leanplum/Leanplum-iOS-SDK#1]
It appears this method, [Leanplum syncResourcesAsync:YES], is not truly Asynchronous.
When I have this method in place, and load my app, I discovered the UI freezes for a couple of seconds while LeanPlum is making some sort of connection/request.

### To Repro:
1. Launch app with above method in place.
2. Interact with UI for a few seconds (Dragging up and down a TableView is a good example)
3. Notice that the UI freezes for a couple seconds, then unfreezes.
4. Remove [Leanplum syncResourcesAsync:YES], then relaunch app and repeat UI interactions.
5. Notice no UI freeze.

**Comment by afirst** [comment]
Thanks for reporting this. This issue was fixed in version 1.2.20.
