### ISSUE TITLE
Library not loaded error after updating to 1.4.0

### ISSUE THREAD

**Issue by ogoog** [Leanplum/Leanplum-iOS-SDK#10]
After upgrading (via cocopoads) to the 1.4.0 version, I get the following error in xcode when my app launches:

`dyld: Library not loaded: @rpath/Leanplum.framework/Leanplum
  Referenced from: /var/containers/Bundle/Application/9FCD1F4A-F251-4C75-91E5-38EFB9115CE5/shoptiques.app/shoptiques
  Reason: image not found`

I upgraded by running the following command:
`pod update Leanplum-iOS-SDK`

**Comment by ogoog** [comment]
Update, in case this helps anyone else:

If I manually add Leanplum.framework to the "Embedded Binaries" for my target under the General tab in xcode, then it works.

**Comment by benmarten** [comment]
Hm, not sure why you are running into this issue. My understanding is that cocoapods handles this.

I tried with a fresh test project. and it works with having `use_frameworks!` or not.

<img width="490" alt="screen shot 2016-09-08 at 10 20 13 am" src="https://cloud.githubusercontent.com/assets/5960238/18359536/39169400-75af-11e6-98eb-c57ed9ce7047.png">
<img width="627" alt="screen shot 2016-09-08 at 10 29 10 am" src="https://cloud.githubusercontent.com/assets/5960238/18359546/3e2c69f6-75af-11e6-9c49-d08776b5ca56.png">

**Comment by benmarten** [comment]
How does your podfile look? Does it add anything to Linked Frameworks and Libraries? My understanding is that Leanplum lib will be bundled in the Pods_<TARGET_NAME>.framework file as shown above...

**Comment by ogoog** [comment]
Hey @benmarten I think this was due to the fact that i was using an old version of cocoapods (0.36) and didn't have a 'target' set in my Podfile. Thanks for the response!

**Comment by benmarten** [comment]
Good to hear, thx for your feedback. Cocoapods 0.39 has added support for dynamic frameworks. Of course the latest is the way to go ;)
