### ISSUE TITLE
Build Error: lipo: -remove i386 specified but fat file: Leanplum does not contain that architecture

### ISSUE THREAD

**Issue by andersryanc** [Leanplum/Leanplum-iOS-SDK#100]
In the setup docs (in the dashboard) it says to add a run script to your project step "7. Strip framework script":

<img width="806" alt="screen shot 2017-11-10 at 11 58 33 am" src="https://user-images.githubusercontent.com/689046/32676221-a2b50f08-c60e-11e7-8803-5c81e676be90.png">

When I try and archive my project I get this error:

<img width="687" alt="screen shot 2017-11-10 at 11 57 28 am" src="https://user-images.githubusercontent.com/689046/32676243-bbe73c94-c60e-11e7-88f5-86d95049303a.png">

Same thing for x86_64 if I remove just `-remove i386` from the run script:

<img width="728" alt="screen shot 2017-11-10 at 12 01 55 pm" src="https://user-images.githubusercontent.com/689046/32676295-f816f43e-c60e-11e7-8aab-f7e8b4b0068f.png">

I installed Leanplum 2.0.3 using carthage. I'm running Swift 4.0.2 in Xcode 9.1 (9B55).

If I remove the run script completely, the archive works as expected... am I alright to leave that out though?

**Comment by alexisoyama** [comment]
This issue should also be addressed by the CSM / TSE.

**Comment by alexisoyama** [comment]
Issues are fixed in new docs: http://www.leanplum.com/docs/ios/setup#install-the-sdk
