### ISSUE TITLE
Update Setup Documentation for Swift 4.0.2

### ISSUE THREAD

**Issue by andersryanc** [Leanplum/Leanplum-iOS-SDK#101]
Not sure this is exactly the right place for this issue, but wasn't sure where else was best to send it...

Your docs both in the account dashboard and [here](https://www.leanplum.com/docs/ios/setup#verify-the-setup) are not up to date with Swift 4.0.2. I was following the setup steps in the account dashboard.

In step 5 "Copy the highlighted statements into your AppDelegate.swift", the imports only include:

```swift
#if DEBUG
        import AdSupport
#endif
```

but I was getting errors like:

<img width="930" alt="screen shot 2017-11-10 at 12 10 42 pm" src="https://user-images.githubusercontent.com/689046/32676642-335b195c-c610-11e7-83c7-5511946ef15e.png">

In order to fix those, I had to add:

```swift
import Leanplum
```

to the top of my file. Similarly, anywhere I was using `Leanplum.track()` I needed to include `import Leanplum`.

Also, in step 5, the docs include the following in it's sample snippet to copy/paste:

```swift
Leanplum.setDeviceId(ASIdentifierManager.sharedManager().advertisingIdentifier.UUIDString)
```

But I was getting this error:

<img width="1015" alt="screen shot 2017-11-10 at 12 12 23 pm" src="https://user-images.githubusercontent.com/689046/32676748-a2fff96c-c610-11e7-8137-652371afaee7.png">

To fix it, I had to change that line to:

```swift
Leanplum.setDeviceId(ASIdentifierManager.shared().advertisingIdentifier.uuidString)
```

I was also running into some issues with Step 7 of the docs in the account dashboard. See #100 for more details.

Are these all valid issues / changes? Or did I do something wrong in my setup? I installed Leanplum 2.0.3 using carthage and am running Swift 4.0.2 in Xcode 9.1 (9B55).

**Comment by alexisoyama** [comment]
Thanks for reporting. CSM and TSE will contact you shortly. We will update our doc.

**Comment by alexisoyama** [comment]
Issues are fixed in new docs: http://www.leanplum.com/docs/ios/setup#install-the-sdk
