### ISSUE TITLE
crash when going into background

### ISSUE THREAD

**Issue by jaz-ah** [Leanplum/Leanplum-iOS-SDK#102]
I'm seeing this crash from crashlytics when users are going into the background.  
Leanplum SDK: 2.0.3
Xcode: 9.1
Frequency: ~20 crashes per day
Looks possibly to coincide with our upgrade to Xcode9.1

<img width="1099" alt="screen shot 2017-11-20 at 6 07 09 am" src="https://user-images.githubusercontent.com/13263369/33022163-152ad49e-cdb9-11e7-8391-25e9a890f898.png">

**Comment by jaz-ah** [comment]
From Xcode:
<img width="690" alt="screen shot 2017-11-20 at 6 18 21 am" src="https://user-images.githubusercontent.com/13263369/33022637-b30c6456-cdba-11e7-9bbe-e7790d953314.png">

**Comment by jaz-ah** [comment]
it looks like we were having these crashes before but they weren't symbolicating correctly/showing up in fabric -here is what showed prior to Xcode9.1 in the Xcode crash dashboard - not much info there:
<img width="690" alt="screen shot 2017-11-20 at 6 18 21 am" src="https://user-images.githubusercontent.com/13263369/33022791-303d75be-cdbb-11e7-8c87-0e1d7e32a645.png">

**Comment by jaz-ah** [comment]
it looks like we were having crashes before but they weren't symbolicating correctly/showing up in fabric -here is what showed prior to Xcode9.1 in the Xcode crash dashboard - not much info there:

<img width="1040" alt="screen shot 2017-11-20 at 6 22 49 am" src="https://user-images.githubusercontent.com/13263369/33022851-4c601e7c-cdbb-11e7-96dd-a84df44d03f3.png">

**Comment by alexisoyama** [comment]
2.0.4 should handle this exception. Please update it and reopen if it is not resolved.

**Comment by jaz-ah** [comment]
ok we'll try it out.

**Comment by alexisoyama** [comment]
Are you able to reproduce this inside Xcode?

**Comment by jaz-ah** [comment]
no, but it looks like this is fixe in 2.0.4
