### ISSUE TITLE
Nullability annotations

### ISSUE THREAD

**Issue by justin** [Leanplum/Leanplum-iOS-SDK#105]
Surprised I didn't see it in the open list, but not having nullability annotations on the Leanplum SDK makes some fields a bit of a guessing game as to what is required vs optional when using it in Swift.

**Comment by alexisoyama** [comment]
Totally valid. It’s good to have it in general. I remember we try to do it a while back but encounter some weird problem. Tracking internally here: https://github.com/Leanplum/Leanplum-iOS-SDK/issues/105
