### ISSUE TITLE
In-framework documentation

### ISSUE THREAD

**Issue by justin** [Leanplum/Leanplum-iOS-SDK#106]
If I read the Leanplum headers in your bundled framework it shows a bit of documentation, but none of it is written in a way that will actually render in Xcode. Would be nice if I could get quick help for the public methods in the framework.

**Comment by alexisoyama** [comment]
This makes sense. We are using doxygen to generate code doc for support center, so we need to validate if there is a format that can do both. Simple change but requires some testing. Will put it in our backlog and I will investigate this further. This is more of a feature request so will close it for now.

**Comment by alexisoyama** [comment]
Tracking internally here
https://leanplum.atlassian.net/browse/LP-7633
