### ISSUE TITLE
Storing __Leanplum.sqlite in Documents

### ISSUE THREAD

**Issue by justin** [Leanplum/Leanplum-iOS-SDK#109]
The __Leanplum.sqlite database that is new as of 2.0.3 is currently stored in the app container's Documents directory, which is reserved for user specific data. 

All other analytics providers, and generally any non-user data, is stored under the Library directory in the container. 

Can this please be added to the fix list?  I realize how pedantic this is, but we are hoping to enable a feature in a future release that uses iCloud Drive and shows that Documents directory for sharing info with us. Having the Leanplum file there is going to be confusing to our users.

**Comment by alexisoyama** [comment]
There are other issues that are more urgent, but will put it in our backlog. Let's discuss outside of this thread which ask is more urgent. I received the compiled feedback from Jeffery.
