### ISSUE TITLE
App Rejected w/ latest sdk: 1.4.0

### ISSUE THREAD

**Issue by jaz-ah** [Leanplum/Leanplum-iOS-SDK#11]
Our app was recently rejected when we added the Leanplum 1.4.0 sdk in - it was rejected for the reason of having a private api: updateLayout

We reverted the sdk back to 1.3.12 and resubmitted to the store and were just approved.

**Comment by benmarten** [comment]
We were not able to find a reference to `updateLayout` in our SDK. Could you send us a little more information please? The full message from Apple would help. You should be able to find it in the Resolution Center in iTunes Connect. Thanks for reporting!

**Comment by jaz-ah** [comment]
From Apple
2. 5 PERFORMANCE: SOFTWARE REQUIREMENTS
Performance - 2.5.1


Your app uses or references the following non-public APIs:

updateLayout:

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

**Comment by benmarten** [comment]
As written earlier I cannot find any reference to the mentioned api within our sdk.
Also googling this method does not give any results related to rejection.

Could you please double check that nothing else has changed since you downgraded?
Maybe do a grep within your project, e.g. `grep -nr '*updateLayout*' .` ?

**Comment by jaz-ah** [comment]
Ben - so interestingly enough we also have a Zendesk sdk that someone had a similar issue with:
https://github.com/zendesk/zendesk_sdk_ios/issues/222
They weren't using a private api but had the same name as one - it's possible that Apple flagged us in the same way and then happened to fix their checker at the same time we resubmitted making it look like leanplum was the issue.. I'll resubmit with the latest leanplum + zendesk sdk's (where they renamed their method) to see if everything is ok.

**Comment by benmarten** [comment]
Thanks!
I am also in the progress of resubmitting our test app with the latest sdk. Normally we do this before we release the SDK, but this time we just didn't get to it in time ;)
