### ISSUE TITLE
Leanplum.onStartResponse called twice when Leanplum server is unreachable

### ISSUE THREAD

**Issue by jtrainer** [Leanplum/Leanplum-iOS-SDK#111]
We're seeing the `Leanplum.onStartResponse` block get called twice when the iOS device has a network connection, but LP is unreachable.

**Environment:**
Leanplum Framework version: 2.0.4
iOS SDK: 11
Xcode 9.2

**Steps to Reproduce:**
1. Connect to a network
2. Edit the network settings in the iOS Settings app > Wi-Fi > [Network Name] > (i) > Configure Proxy
3. Set Proxy to "Manual"
4. Set Server to an unused IP Address. (e.g. 10.0.0.1)
5. Set break point inside the custom `.onStartResponse` block
6. Make sure `Leanplum.start()` is called
7. Debug app in Xcode and wait for callback to get called two times.

**Comment by alexisoyama** [comment]
Thanks. It might be related to https://github.com/Leanplum/Leanplum-iOS-SDK/issues/99. Will test and confirm.

**Comment by alexisoyama** [comment]
Should be fixed by https://github.com/Leanplum/Leanplum-iOS-SDK/pull/116. Released in 2.0.5
