### ISSUE TITLE
Crash on presenting image picker of photo library with syncResourcesAsync on iOS 10.0

### ISSUE THREAD

**Issue by rizumita** [Leanplum/Leanplum-iOS-SDK#12]
Apps crash on presenting image picker controller of photo library source with Leanplum iOS SDK 1.4.0.1 on iOS 10.0 if Leanplum.syncResourcesAsync method called.

I tried with my app and a new app of single view project. Both crashed.

By Leanplum.syncResourcesAsync method not called, the apps didn't crash.

**Comment by benmarten** [comment]
Thanks for reporting the issue. I just tried to reproduce your issue, but I can't. It is working for me, e.g. not crashing.

Here's my test code:
    //
    //  ViewController.m
    //  test
    //
    //  Created by Ben on 10/5/16.
    //  Copyright © 2016 colibriapps. All rights reserved.
    //

    #import "ViewController.h"
    #import <Leanplum/Leanplum.h>

    @interface ViewController()

    @property UIImage *image;
    @property (weak, nonatomic) IBOutlet UIImageView *imageView;

    @end

    @implementation ViewController

    - (void)viewDidLoad {
        [super viewDidLoad];

        [Leanplum setAppId:@"app_BWTRIgOs0OoevDfSsBtabRiGffu5wOFU3mkxIxA7NBs" withDevelopmentKey:@"dev_Bx8i3Bbz1OJBTBAu63NIifr3UwWqUBU5OhHtywo58RY"];
        [Leanplum syncResourcesAsync:YES];
        [Leanplum start];
        // Do any additional setup after loading the view, typically from a nib.
    }

    - (void)viewDidAppear:(BOOL)animated {
        [super viewDidAppear:animated];
        if (!_image) {
            [self showImagePicker];
        }
    }

    - (void)didReceiveMemoryWarning {
        [super didReceiveMemoryWarning];
        // Dispose of any resources that can be recreated.
    }

    - (void)showImagePicker {
        UIImagePickerController *picker = [[UIImagePickerController alloc] init];
        picker.delegate = self;
        picker.allowsEditing = YES;
        picker.sourceType = UIImagePickerControllerSourceTypePhotoLibrary;

        [self presentViewController:picker animated:YES completion:nil];
    }

    - (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info {

        _image = info[UIImagePickerControllerEditedImage];
        [_imageView setImage:_image];
        [picker dismissViewControllerAnimated:YES completion:nil];
    }

    @end

Providing a stack trace and/or sample code is very much appreciated too!

**Comment by rizumita** [comment]
@benmarton 
Thank you for trying.
What version of Xcode did you use?
I used Xcode7.3.1.

**Comment by benmarten** [comment]
We are using Xcode Version 8.0 (8A218a).

**Comment by benmarten** [comment]
I hope this works now, please reopen if not ;)

**Comment by seanrogs** [comment]
This is also crashing for me on the latest SDK. It took a couple of days to track down as I was not aware Leanplum hooked in to the user's photo library at all.

I'm using Swift: our main app is Swift 2.3, the sample code below is Swift 3. Note that the crash only occurs on devices running iOS 10, not in the simulator.

```
import UIKit
import Leanplum

class ViewController: UIViewController, UIImagePickerControllerDelegate, UINavigationControllerDelegate {
    
    @IBOutlet weak var imageView: UIImageView!
    var image: UIImage?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        Leanplum.setAppId("", withProductionKey: "")
        Leanplum.syncResourcesAsync(true)
        Leanplum.start()
    }
    
    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        if image == nil {
            showImagePicker()
        }
    }

    func showImagePicker() {
        let picker = UIImagePickerController()
        picker.delegate = self
        picker.sourceType = .PhotoLibrary
        presentViewController(picker, animated: true, completion: nil)
    }
    
    func imagePickerController(picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : AnyObject]) {
        if let imageInfo = info[UIImagePickerControllerEditedImage] as? UIImage {
            image = imageInfo
            imageView.image = image
            picker.dismissViewControllerAnimated(true, completion: nil)
        }
    }
}
```

**Comment by seanrogs** [comment]
@benmarten I think this issue is worth reopening based on my above post.

**Comment by gigasmile** [comment]
@seanrogs Thanks. I will test it on the device and see what's going on.

**Comment by rizumita** [comment]
@seanrogs 
When I happened to meet the crash, by comment out following code the app became not to crash.
```
Leanplum.syncResourcesAsync(true)
```
How about with your app?

**Comment by benmarten** [comment]
Ok, I can confirm that the crash is happening also with my Obj-C project, but only on real Device. commenting the `Leanplum.syncResourcesAsync()` method makes it work again.

```
2016-11-23 11:02:08.057696 test[11914:4944456] [error] error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///var/mobile/Media/PhotoData/Photos.sqlite?readonly_shm=1 options:{
    NSPersistentStoreFileProtectionKey = NSFileProtectionCompleteUntilFirstUserAuthentication;
    NSReadOnlyPersistentStoreOption = 1;
    NSSQLitePersistWALOption = 1;
    NSSQLitePragmasOption =     {
        "journal_mode" = WAL;
    };
} ... returned error Error Domain=NSCocoaErrorDomain Code=256 "The file couldn’t be opened." UserInfo={reason=Failed to access file: 1} with userInfo dictionary {
    reason = "Failed to access file: 1";
}
2016-11-23 11:02:08.057910 test[11914:4944456] [Migration] Unexpected error opening persistent store file:///var/mobile/Media/PhotoData/Photos.sqlite?readonly_shm=1, cannot attempt migration Error Domain=NSCocoaErrorDomain Code=256 "The file couldn’t be opened." UserInfo={reason=Failed to access file: 1})
2016-11-23 11:02:08.058161 test[11914:4944456] [Migration] Failed to open store /var/mobile/Media/PhotoData/Photos.sqlite.  Requires update via assetsd (256: The file couldn’t be opened.)
2016-11-23 11:02:08.058622 test[11914:4944456] [error] error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///var/mobile/Media/PhotoData/Photos.sqlite?readonly_shm=1 options:{
    NSPersistentStoreFileProtectionKey = NSFileProtectionCompleteUntilFirstUserAuthentication;
    NSReadOnlyPersistentStoreOption = 1;
    NSSQLitePersistWALOption = 1;
    NSSQLitePragmasOption =     {
        "journal_mode" = WAL;
    };
} ... returned error Error Domain=NSCocoaErrorDomain Code=256 "The file couldn’t be opened." UserInfo={reason=Failed to access file: 1} with userInfo dictionary {
    reason = "Failed to access file: 1";
}
2016-11-23 11:02:08.058708 test[11914:4944456] [Migration] Store open/configuration failed on 2nd attempt: Error Domain=NSCocoaErrorDomain Code=256 "The file couldn’t be opened." UserInfo={reason=Failed to access file: 1}

```

We are looking into the issue. We'll update here as soon as we know when we can deliver a fix.

**Comment by gigasmile** [comment]
We found the bug and the fix will be in the next release. Will update again when the release is landed. Please disable syncResourcesAsync for now.

**Comment by gigasmile** [comment]
This is fixed from 1.4.2.

**Comment by edenman** [comment]
@gigasmile can you share what the fix was?

**Comment by benmarten** [comment]
It was an issue in swizzling the bundlepath:
```
+++ b/Leanplum-SDK/Leanplum-SDK/Classes/LPFileManager.m
@@ -38,9 +38,9 @@ @implementation NSBundle (LeanplumExtension)
 + (NSBundle *)leanplum_mainBundle
 {
     if (skippedFiles.count) {
-        return [LPBundle bundleWithPath:[LPFileManager bundlePath]];
+        return [LPBundle bundleWithPath:[originalMainBundle bundlePath]];
     } else {
-        return [NSBundle bundleWithPath:[LPFileManager bundlePath]];
+        return originalMainBundle;
     }
 }
```
