### ISSUE TITLE
SQLite errors on tvOS

### ISSUE THREAD

**Issue by krzemienski** [Leanplum/Leanplum-iOS-SDK#120]
## Expected Behavior
I'm having some issues with leanplum for tvOS I keep getting an error where we are unable to speak to what looks like a sqlite db. https://github.com/Leanplum/Leanplum-iOS-SDK/issues/109

I noticed you guys actually changed the location of this sqlite to Documents and I believe on tvOS you cant write to the documents it might have to be the library path. Below is the console log of errors I am receiving when trying to run on tvOS.

## Actual Behavior
When attempting to start the leanplum sdk I receive these errors -

```Leanplum ERROR: SQLite fail to open: unable to open database file (14)
Leanplum ERROR: SQLite fail to prepare: 'SELECT count(*) FROM event;' unable to open database file (21)

Leanplum ERROR: SQLite fail to prepare: 'INSERT INTO event (data) VALUES (?);' unable to open database file (21)

Leanplum ERROR: SQLite fail to prepare: 'SELECT data FROM event ORDER BY rowid LIMIT 10000' 
Leanplum ERROR: SQLite fail to prepare: 'SELECT count(*) FROM event;' unable to open database file (21)

Leanplum ERROR: SQLite fail to prepare: 'INSERT INTO event (data) VALUES (?);' unable to open database file (21)```

## Steps to Reproduce the Problem

  1. Download the sample tvos sdk v2.0.5
  2. Add in keys
  3. Run from Xcode

## Specifications

  - Version: 2.0.5
  - Platform: tvOS 11.2.1

**Comment by alexisoyama** [comment]
This error is quite weird. It works in the simulator but not on the device. 
I moved sqlite to Library but I'm still having this error. /var/mobile/Containers/Data/Application/6BFA4D59-F377-47CA-A514-FEB33BF5D98F/Library/__leanplum.sqlite

Will need to investigate further. Let me know if you have some other insights.

**Comment by alexisoyama** [comment]
tvOS does not allow access to any persistent directories: Directory and Library. You can only put the files in the cache directory. However, this is can only be reproduced on device and it works in the simulator. 

The fix is in https://github.com/Leanplum/Leanplum-iOS-SDK/pull/128/.
Your prime contact will provide you with a Charity Build.

**Comment by krzemienski** [comment]
@alexisoyama yup I figured it was the documents issue! Thank you for handling
