### ISSUE TITLE
Unable to compile on xCode 9.3

### ISSUE THREAD

**Issue by matt-OfferUp** [Leanplum/Leanplum-iOS-SDK#133]
## Expected Behavior
Should be able to compile

## Actual Behavior
Errors while trying to compile
"Could not build module Leanplum"
"Macro expansion producing 'defined' has undefined behavior"
This is for LP_NOT_TV in Leanplum.h

## Steps to Reproduce the Problem

  1. Download xCode 9.3
  2. Attempt to build the project

## Specifications

  - Version: 2.0.2 and 2.0.5 from cocoapods using xCode 9.3
  - Platform: iOS
  - Subsystem:

**Comment by jaz-ah** [comment]
+1 getting same error

**Comment by benmarten** [comment]
This is not reproducible for me, I tried the following steps inside this repo:
```
cd Example
pod install
open Leanplum-SDK.xcworkspace
```
Clean and build, succeeds. I'm on macOS 10.13.3 and Xcode 9.3 (9E145).

Please let me know how to reproduce this?

**Comment by matt-OfferUp** [comment]
It appears that in xCode 9.3 (!defined(TARGET_OS_TV) || !TARGET_OS_TV) does not equate to 1 or 0. 

Changing 
```
#ifndef LP_NOT_TV
#define LP_NOT_TV (!defined(TARGET_OS_TV) || !TARGET_OS_TV)
#endif
```
to 
```
#ifndef LP_NOT_TV
#if (!defined(TARGET_OS_TV) || !TARGET_OS_TV)
#define LP_NOT_TV 1
#else
#define LP_NOT_TV 0
#endif
#endif
```
in Leanplum.h fixes the issue for us. (ugly I know)

**Comment by benmarten** [comment]
Thanks for your feedback, which Xcode version are you using?

**Comment by benmarten** [comment]
How are you opening the SDK? (https://github.com/Leanplum/Leanplum-iOS-SDK#installation--usage)

**Comment by jaz-ah** [comment]
@benmarten Leanplum also is providing clients the files LPMessageTemplates.h/m in order to display in app messages, etc... - it is in these files that the compiler error occurs w/ XCode9.3

**Comment by matt-OfferUp** [comment]
We are using cocoa pods, though I'm not sure that would have any affect on this type of error.

**Comment by NSMyself** [comment]
I'm having the same issues when installing via Carthage.
Here's my Cartfile:

`github "Leanplum/Leanplum-iOS-SDK"`

and here's a piece of the output:

```
** Skipped building Leanplum-iOS-SDK due to the error:
Dependency "Leanplum-iOS-SDK" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at Optional("https://github.com/Leanplum/Leanplum-iOS-SDK/issues/new")
/Users/nsmyself/lp/Carthage/Checkouts/FSPagerView/Sources/FSPageControl.swift:110:13: warning: switch must be exhaustive
/Users/nsmyself/lp/Carthage/Checkouts/FSPagerView/Sources/FSPageControl.swift:110:13: warning: switch must be exhaustive
/Users/nsmyself/lp/Carthage/Checkouts/FSPagerView/Sources/FSPageControl.swift:110:13: warning: switch must be exhaustive
/Users/nsmyself/lp/Carthage/Checkouts/FSPagerView/Sources/FSPageControl.swift:110:13: warning: switch must be exhaustive
/Users/nsmyself/lp/Carthage/Checkouts/HanekeSwift/Haneke/Data.swift:43:35: warning: using '!' in this location is deprecated and will be removed in a future release; consider changing this to '?' instead
/Users/nsmyself/lp/Carthage/Checkouts/HanekeSwift/Haneke/CryptoSwiftMD5.swift:39:18: warning: 'deinitialize()' is deprecated: the default argument to deinitialize(count:) has been removed, please specify the count explicitly
/Users/nsmyself/lp/Carthage/Checkouts/HanekeSwift/Haneke/CryptoSwiftMD5.swift:40:18: warning: 'deallocate(capacity:)' is deprecated: Swift currently only supports freeing entire heap blocks, use deallocate() instead
/Users/nsmyself/lp/Carthage/Checkouts/HanekeSwift/Haneke/Data.swift:43:35: warning: using '!' in this location is deprecated and will be removed in a future release; consider changing this to '?' instead
/Users/nsmyself/lp/Carthage/Checkouts/HanekeSwift/Haneke/CryptoSwiftMD5.swift:39:18: warning: 'deinitialize()' is deprecated: the default argument to deinitialize(count:) has been removed, please specify the count explicitly
/Users/nsmyself/lp/Carthage/Checkouts/HanekeSwift/Haneke/CryptoSwiftMD5.swift:40:18: warning: 'deallocate(capacity:)' is deprecated: Swift currently only supports freeing entire heap blocks, use deallocate() instead
A shell task (/usr/bin/xcrun xcodebuild -project /Users/nsmyself/lp/Carthage/Checkouts/mixpanel-iphone/Mixpanel.xcodeproj -scheme "[App Extension] Mixpanel" -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme [App Extension] Mixpanel is not currently configured for the clean action.
```

**Comment by jtrainer** [comment]
We're seeing this too.

LP SDK 2.0.5 
Xcode 9.3 (9E145)
Cocoapods 1.4.0

**Comment by adhumi** [comment]
We also experience the issue, this various configurations (Cocoapods or Carthage, both with Xcode 9.3).

@benmarten If that helps, we were able to reproduce the issue with a new Objective-C project in Xcode 9.3 using Carthage. Just create the project, add Leanplum and `@import` it in any file.

**Comment by e7mac** [comment]
definitely working in XCode 10 now
