### ISSUE TITLE
Core Location prompt on launch

### ISSUE THREAD

**Issue by danielphillips** [Leanplum/Leanplum-iOS-SDK#14]
V1.4 and newer automatically Asks location permission on setup, this means when our app is launched we get a prompt. We had deliberately deferred this prompt to improve both the onboarding and the likelihood that the users grants permissions since it's now in a location dependant area in the app.

However since updating to v1.4.x of leanplum, we are seeing location prompt on launch. 

Please provide a hook to disable this behaviour. I want location for my users but I cannot accept an upfront request and I prefer to not have location for some users.

**Comment by gigasmile** [comment]
You can set authorizeAutomatically to false in LPLocationManager to handle this.

**Comment by gigasmile** [comment]
@danielphillips Let me know if you have any other question regarding this. Will close it for now.
