### ISSUE TITLE
Why [[Leanplum newsfeed] onChanged:^{}] can not refresh messages?

### ISSUE THREAD

**Issue by carlosbdw** [Leanplum/Leanplum-iOS-SDK#15]
Hi ,it seems that the block does not work, even we wait for more than 10 minutes , we have to kill the app and open it again ,then we can receive the new messages, any idea to improve it ? We just want to refresh our tableview when receive new messages.

**Comment by gigasmile** [comment]
All messages, including in-app and newsfeed messages, are downloaded on [Leanplum start] and [Leanplum forceContentUpdate]. 
If forceContentUpdate successfully downloads new newsfeed messages, it should call onChanged:.

**Comment by carlosbdw** [comment]
Thank you for reply, If I call [Leanplum forceContentUpdate] , it will refresh all variables and messages ,does it affect on the exist A/B test result?

**Comment by gigasmile** [comment]
Sorry to get back to you late. Yes, forceContentUpdate will update the variants. Closing this issue. 
If you want to ask for a feature please contact our support :)
