### ISSUE TITLE
Historical messages are not retrieved 

### ISSUE THREAD

**Issue by carlosbdw** [Leanplum/Leanplum-iOS-SDK#16]
What I noticed in my testing on my iPhone is that when I login with an existing userId after delete the old app and reinstall ,the historical messages are not retrieved neither on StartLeanplum nor forceContentUpdate. I made sure these messages were not marked as read or deleted. It seems like a issue come from Leanplum backend.

**Comment by gigasmile** [comment]
Atanas reported this issue and I believe he is in middle of the investigation. He will update you once we get to the bottom of it.
