### ISSUE TITLE
carthage not buid Leanplum-iOS-SDK

### ISSUE THREAD

**Issue by ikzjfr0** [Leanplum/Leanplum-iOS-SDK#18]
in Cartfile, i have
 github "Leanplum/Leanplum-iOS-SDK" "1.7.0"

then i ran
carthage update --platform iOS --no-use-binaries

NO Leanplum build action is found and there's no output in the folder of /Carthage/Build/iOS

**Comment by milos1290** [comment]
Hi, here is the short doc on how to specify specific version in Cartfile
```
Carthage supports several kinds of version requirements:
>= 1.0 for “at least version 1.0”
~> 1.0 for “compatible with version 1.0”
== 1.0 for “exactly version 1.0”
"some-branch-or-tag-or-commit" for a specific Git object (anything allowed by git rev-parse)
```

so in your example it would be something like this

```
github "Leanplum/Leanplum-iOS-SDK" == 1.7.0
```

**Comment by benmarten** [comment]
Did you try without: `--no-use-binaries`. Leanplum SDK is closed source currently.

**Comment by ikzjfr0** [comment]
that's clear, thanks :)
