### ISSUE TITLE
iOS SDK 1.3.1 viewWillAppear not trigger

### ISSUE THREAD

**Issue by Hokila** [Leanplum/Leanplum-iOS-SDK#2]
I have a tabBarController contain 5 tab,each tab is a navigationController,
viewControllers under navigation will not trigger viewWillAppear,
but it's work in 1.2.23, maybe not callback when using method swizzling.

**Comment by paulb777** [comment]
Thanks for the bug report.

Are you be able to provide more detail about your use case, or better yet, sample code that illustrates the issue?

I verified that that the viewWillAppear calls do occur in the sample at https://github.com/paulb777/RecipeBookWithLeanplum

**Comment by Hokila** [comment]
I found viewWillAppear will not call at particular case only if use leanplum 1.3.1 and Reveal in the same project,it is not happen every time.also sometimes it's not affect every inheritance viewController. 

simple solution is just not use reveal.
I close this issue

**Comment by Hokila** [comment]
sorry ,I found even I remove reveal ,problem still exist.
reopen this issue

**Comment by paulb777** [comment]
Thanks for sharing your investigation results. 

Is there anything more you can say about the problem? Is it always the same view? Where does that view fit in the view hierarchy? Does it matter which view appeared most recently?

**Comment by Hokila** [comment]
I have try some sample project,they all call viewWillAppear.But in my product project it not called.
 It's occur with some framework work with leanplum together.I'm still investigating.

**Comment by Hokila** [comment]
all my viewcontrollers inheritance from UIViewController will not get called. frequency is 100%.

**Comment by paulb777** [comment]
Are you able to share the current view hierarchy when the problem occurs? One way to do that is po [[UIWindow keyWindow] recursiveDescription] in the debugger. See http://stackoverflow.com/questions/5150186/how-do-i-inspect-the-view-hierarchy-in-ios

**Comment by Hokila** [comment]
HI @paulb777 
my colleague zonble just write a sample code can reproduce this issue,please help check
https://github.com/zonble/RecipeBookWithLeanplum 

tap SubClassOfRecipeBookViewController more than two times,RecipeDetailViewController  viewWillAppear wil not get called

**Comment by paulb777** [comment]
Thanks for the great testcase!

I've made a fix and we should have an updated SDK available by early next week.

**Comment by paulb777** [comment]
Fixed in 1.3.4.

**Comment by Hokila** [comment]
thanks ,problem is sloved
