### ISSUE TITLE
Leanplum 2.2.0 binary release for Carthage

### ISSUE THREAD

**Issue by rpassis** [Leanplum/Leanplum-iOS-SDK#231]
Hi all 

Our Carthage builds are failing because we updated to 2.2.0 but there are no binaries made available for that tag, and we obviously can't build from source.

Could you please add a binary release to the 2.2.0 tag?

Thanks!
Rog

**Comment by justin** [comment]
Not to add a "me too" on top of this, but we wanted to integrate the new callback that was added in the 2.2 version of the SDK for our current release because it matched a request perfectly, but are unable to because we can't update via Carthage.

**Comment by thad** [comment]
+1

**Comment by e7mac** [comment]
Just added the binary to the release. Please could you let me know if that's working for you now? We've been moving away from a legacy build system hence the pains. However, I'm committed to getting you all set up again asap.

**Comment by rpassis** [comment]
That worked, thank you!

**Comment by rpassis** [comment]
Actually I take it back.

The binary attached to this release excludes x86 architecture so we are unable to build the app for the simulator:

```
$ lipo -info Leanplum.framework/Leanplum
Architectures in the fat file: Leanplum.framework/Leanplum are: armv7 arm64 
```

**Comment by thad** [comment]
I'm getting the same issue as @rpassis

**Comment by e7mac** [comment]
I see. I'll upload one with all those architectures today

**Comment by e7mac** [comment]
Thanks everyone for the patience. I just uploaded a new build with the missing architectures for the simulator. Please let me know if that worked or not.

Side note: Could you please help me understand what you add in the `Cartfile`? This will help me ensure that it works on my end too.

**Comment by rpassis** [comment]
Thanks @e7mac 

Here's what my Cartfile would look like if I only wanted to download Leanplum as a dependency for my project:

```
github "Leanplum/Leanplum-iOS-SDK" ~> 2.2.0
```

**Comment by e7mac** [comment]
Closing this issue. Please let me know of any other issues.
