### ISSUE TITLE
Carthage SDK isn't compiled with Bitcode enabled.

### ISSUE THREAD

**Issue by justin** [Leanplum/Leanplum-iOS-SDK#232]
## Expected Behavior

This is a regression from past behavior where Bitcode was enabled for the frameworks.

When we try to upload a new binary now we receive the following error:

> [10:47:10]: ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "TED.app/Frameworks/Leanplum.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains arm64(bitcode), while the nested bundle Mach-O contains armv7(machine code) and armv7s(machine code) and arm64(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."

## Specifications

  - Version: 2.2
  - Platform: iOS

**Comment by justin** [comment]
Thanks for looking into it. I just downloaded the latest version and it still seems to be returning the same error when I try to upload.

**Comment by e7mac** [comment]
`lipo` was giving me grief in combining but I think I have it figured out now. Please give the new binary a shot and let me know if that works. Thanks for your patience.

**Comment by justin** [comment]
I just downloaded the newest binary and now get compilation errors on launch about `LPMessageArchiveData.h` not being found.

**Comment by e7mac** [comment]
Sorry this has been so tedious. I've added all the missing headers and think this should be the golden build. Also, this has helped me iron out the build script so updates should be smooth going forward. Thanks again for being patient.

**Comment by justin** [comment]
It looks like we have a winner. Thank you for the effort!
