### ISSUE TITLE
Crash Reports

### ISSUE THREAD

**Issue by justin** [Leanplum/Leanplum-iOS-SDK#236]
This isn't so much a bug report as a question: are crash reports helpful for you? We can't symbolicate anything in Xcode or MS App Center that requires the Leanplum dSYM, but i can pass them on if you're interested in crashes?

thx.

**Comment by nzagorchev** [comment]
Hi,

They are helpful. The crash reports can be symbolicated using the dsym of the SDK version used in the crash report.

If you would like to report a crash, please submit a support ticket.
