### ISSUE TITLE
Trying to find LPInternalMessageTemplates.

### ISSUE THREAD

**Issue by kirillyakimovich** [Leanplum/Leanplum-iOS-SDK#243]
Hi guys, in the process of integrating framework I've encountered a class named `LPInternalMessageTemplates`, but I'm unable to find it anywhere. 
Could you please clarify, or point me to it.

**Comment by e7mac** [comment]
@kirillyakimovich this should now be working. Please give it a shot and let us know if not. Thanks!

**Comment by kirillyakimovich** [comment]
Just checked your recent commits and there is nothing related to `LPInternalMessageTemplates`

**Comment by e7mac** [comment]
We updated the uploaded binary for 2.2.1. Are you integrating through Carthage or Cocoapods?

**Comment by e7mac** [comment]
Also, I looked for that class but didn't find an exact match, could you help me understand where you found it. Thanks!
