### ISSUE TITLE
Could not build module Leanplum 2.2.1

### ISSUE THREAD

**Issue by volkdmitri** [Leanplum/Leanplum-iOS-SDK#244]
`Leanplum.h` line 30 `LPMessageArchiveData.h file not found`.

**Comment by hrishileanplum** [comment]
@volkdmitri  can you please try "pod cache clean --all" or "pod update" and let us know if that fixes it. Also, if you can specify how your pod file looks.

**Comment by volkdmitri** [comment]
I use a pre-compiled framework attached to releases instead of CocoaPods. Sorry for missing this point.

**Comment by hrishileanplum** [comment]
Thanks for sharing this information @volkdmitri . 
Can you please make sure that your library was compiled without bitcode, but the bitcode option is enabled in your project settings.
Say NO to **Enable Bitcode** in your target Build Settings and the Library Build Settings to remove the warnings.

If this works?

**Comment by hrishileanplum** [comment]
Also, let me check on the pre-compiled framework as well.

**Comment by volkdmitri** [comment]
> Thanks for sharing this information @volkdmitri .
> Can you please make sure that your library was compiled without bitcode, but the bitcode option is enabled in your project settings.
> Say NO to **Enable Bitcode** in your target Build Settings and the Library Build Settings to remove the warnings.
> 
> If this works?

Sorry, but it seems that the issue is not related to bitcode settings, anyway it is disabled. As I previosly said, I just link the framework attached to Gihub releases. Thank you.

**Comment by e7mac** [comment]
Thanks for reporting this @volkdmitri. I've uploaded a new binary that should fix the issue. Let me know if it works!

**Comment by volkdmitri** [comment]
Yes, the issue is fixed. Thank you.
