### ISSUE TITLE
crash w/ leanplum sdk 2.2.1

### ISSUE THREAD

**Issue by jaz-ah** [Leanplum/Leanplum-iOS-SDK#248]
## Expected Behavior
Not to crash

## Actual Behavior
crashes w/ lp sdk

## Steps to Reproduce the Problem

No clear reproducible steps - we are getting lots of crash reports through crashlytics, but they always seem to appear when the application is resigning active state (applicationWillResignActive) as we can see through our breadcrumbs.

## Specifications

  - Version: iOS sdk 2.2.1
  - Platform: iOS on at least iOS11 and 12
  - Subsystem: does not seem to be limited to a specific device/model/etc... 

```

0 | libobjc.A.dylib | objc_msgSend + 8
-- | -- | --
1 | CoreFoundation | -[__NSDictionaryM setObject:forKeyedSubscript:] + 524
2 | Leanplum | LPEventCallbackManager.m line 59+[LPEventCallbackManager addEventCallbackAt:onSuccess:onError:]
3 | Leanplum | LeanplumRequest.m line 437-[LeanplumRequest sendEventually]
4 | Leanplum | LeanplumRequest.m line 255-[LeanplumRequest sendNow:]
5 | Leanplum | LeanplumRequest.m line 409-[LeanplumRequest sendNow]
6 | Leanplum | LeanplumRequest.m line 232-[LeanplumRequest sendIfConnectedSync:]
7 | Leanplum | LeanplumRequest.m line 214-[LeanplumRequest sendIfConnected]
8 | Leanplum | LPRequestSender.m line 161-[LPRequestSender sendIfConnected:]
9 | Leanplum | Leanplum.m line 1196+[Leanplum pause]
10 | Leanplum | Leanplum.m line 1028__59+[Leanplum startWithUserId:userAttributes:responseHandler:]_block_invoke.606
11 | Foundation | -[__NSObserver _doit:] + 316
42 | UIKitCore | UIApplicationMain + 212
43 | Activehours | main + 148
44 | libdyld.dylib | start + 4
```

**Comment by pcki11** [comment]
Happened for me as well. Crashed on iOS 12.2.0, SDK version 2.4.1

`
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000001a1deb46da5

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1a43cf6a8 objc_msgSend + 8
1  CoreFoundation                 0x1a509f750 -[__NSDictionaryM setObject:forKeyedSubscript:] + 552
2  ???                            0x4a39010316d16c (Missing)
3  Leanplum                       0x10315a9ec -[LeanplumRequest sendEventually] (LeanplumRequest.m:424)
4  Leanplum                       0x103159838 -[LeanplumRequest sendNow:] (LeanplumRequest.m:242)
5  Leanplum                       0x10315a7c0 -[LeanplumRequest sendNow] (LeanplumRequest.m:396)
6  Leanplum                       0x1031595c4 -[LeanplumRequest sendIfConnectedSync:] (LeanplumRequest.m:219)
7  Leanplum                       0x1031593f4 -[LeanplumRequest sendIfConnected] (LeanplumRequest.m:201)
8  Leanplum                       0x1031886ec -[LPRequestSender sendIfConnected:] (LPRequestSender.m:162)
9  Leanplum                       0x103141c14 +[Leanplum pause] (Leanplum.m:1195)
10 Leanplum                       0x103140a90 __59+[Leanplum startWithUserId:userAttributes:responseHandler:]_block_invoke.573 (Leanplum.m:1033)
11 Foundation                     0x1a5b42814 -[__NSObserver _doit:] + 336`
