### ISSUE TITLE
Unclear how to build the SDK from source

### ISSUE THREAD

**Issue by st3fan** [Leanplum/Leanplum-iOS-SDK#26]
(Mozilla / Firefox)

It is unclear how to build the SDK from source code

- The `_Pods.xcodeproj` does not build from Xcode
- The `master` and `develop` branches have a `build.sh` script but it fails
- The `releases/2.0.1` branch has no `build.sh`

Can you please provide documentation or assistance on how to build the *Leanplum.framework* from the source code?

**Comment by benmarten** [comment]
we are running `build.sh` ourselves. I just tested and its working. It might be because of some missing dependencies. What's the error you are getting?

**Comment by benmarten** [comment]
try:
```
cd Example && pod install
cd - && ./build.sh
```
