### ISSUE TITLE
Leanplum utilizes bitcode by default and causes errors to occur for other non bitcode pods

### ISSUE THREAD

**Issue by kyleleanplum** [Leanplum/Leanplum-iOS-SDK#266]
Leanplum SDK utilizes Bitcode generation forced into Xcode project. This is as a result of the .podspec ->
https://github.com/Leanplum/Leanplum-iOS-SDK/blob/702cce97404e9aca15f5554139f337a6ca0a4cc4/Leanplum-iOS-SDK.podspec#L30

Errors Received:
`bitcode bundle could not be generated because '<PATH_TO_POD_WITHOUT_BITCODE>' was built without full bitcode`.

As a user not utilizing Bitcode generation I either have to change this in Xcode after every `pod install` or `pod update`. An alternative to fix is to always implement something on the pod level to change the flag of `BITCODE_GENERATION_MODE` to either `marker` or `no`.

## Specifications

  - Version: SDK Version 2.2.+
  - Platform: iOS
  - Subsystem: Cocoapods

**Comment by hbanzon** [comment]
@kyleleanplum

I'm still experiencing this issue after attempting to update to SDK Version 2.4.0.  Any idea when it might be fixed?

Thanks,
Hino

**Comment by e7mac** [comment]
@hbanzon while we're looking into this, have you tried the option here to override the config settings in the `Podfile`? https://stackoverflow.com/questions/32640149/disable-bitcode-for-project-and-cocoapods-dependencies-with-xcode7

**Comment by hbanzon** [comment]
@e7mac thank you for quick response.  We have evaluated this option and we need this fixed instead in order for us to update beyond v2.1.x of the SDK.

**Comment by e7mac** [comment]
The release 2.4.1 has this fixed
