### ISSUE TITLE
Xcode 7 Beta 3 + iOS 9 Beta 3

### ISSUE THREAD

**Issue by karthikkeyan** [Leanplum/Leanplum-iOS-SDK#3]
Im getting compile error when trying to run the app. It was working fine with 1.3.3. Im seeing this error after i update the version to 1.3.6 using cocopods.

Now i want go back to 1.3.3, but cocoa pods couldn't find the that version. Im receiving this error from pods "[!] Unable to find a specification for `Leanplum-iOS-SDK1.3.3`".

Compiler Error : 
Ld /Users/ymedialabs/Library/Developer/Xcode/DerivedData/Tableaux-ebmgmudfgnxeywcrugwznpisqeaq/Build/Products/PreProd-iphoneos/Tableaux.app/Tableaux normal arm64
    cd /Users/ymedialabs/Documents/Projects/Staples/iphone
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -L/Users/ymedialabs/Library/Developer/Xcode/DerivedData/Tableaux-ebmgmudfgnxeywcrugwznpisqeaq/Build/Products/PreProd-iphoneos -L/Users/ymedialabs/Documents/Projects/Staples/iphone/Pods/CardIO/CardIO -L/Users/ymedialabs/Documents/Projects/Staples/iphone/Pods/CrittercismSDK/CrittercismSDK -L/Users/ymedialabs/Documents/Projects/Staples/iphone/Tableaux/Library/Helpers/ThirdParty/AdobeMobileLibrary -L/Users/ymedialabs/Documents/Projects/Staples/iphone/Airship -F/Users/ymedialabs/Library/Developer/Xcode/DerivedData/Tableaux-ebmgmudfgnxeywcrugwznpisqeaq/Build/Products/PreProd-iphoneos -F/Users/ymedialabs/Documents/Projects/Staples/iphone/Pods/GoogleAppIndexing/Frameworks -F/Users/ymedialabs/Documents/Projects/Staples/iphone/Pods/Leanplum-iOS-SDK -F/Users/ymedialabs/Documents/Projects/Staples/iphone/Tableaux/Frameworks -filelist /Users/ymedialabs/Library/Developer/Xcode/DerivedData/Tableaux-ebmgmudfgnxeywcrugwznpisqeaq/Build/Intermediates/Tableaux.build/PreProd-iphoneos/Tableaux.build/Objects-normal/arm64/Tableaux.LinkFileList -miphoneos-version-min=8.0 -dead_strip -ObjC -lCardIO -lCrittercism_v5_2_0 -lPods-AFNetworkActivityLogger -lPods-AFNetworking -lPods-CocoaLumberjack -lPods-Lockbox -lPods-Mantle -lPods-UIAlertView+Blocks -lPods-apptentive-ios -lc++ -framework AVFoundation -framework Accelerate -framework AssetsLibrary -framework AudioToolbox -framework CFNetwork -framework CoreData -framework CoreGraphics -framework CoreMedia -framework CoreText -framework CoreVideo -framework Foundation -framework GoogleAppIndexing -framework Leanplum -framework MobileCoreServices -framework OpenGLES -framework QuartzCore -framework Security -framework SystemConfiguration -framework UIKit -weak_framework AdSupport -weak_framework CoreTelephony -weak_framework StoreKit -ObjC -lCardIO -lCrittercism_v5_2_0 -lPods-AFNetworkActivityLogger -lPods-AFNetworking -lPods-CocoaLumberjack -lPods-Lockbox -lPods-Mantle -lPods-UIAlertView+Blocks -lPods-apptentive-ios -lc++ -framework AVFoundation -framework Accelerate -framework AssetsLibrary -framework AudioToolbox -framework CFNetwork -framework CoreData -framework CoreGraphics -framework CoreMedia -framework CoreText -framework CoreVideo -framework Foundation -framework GoogleAppIndexing -framework Leanplum -framework MobileCoreServices -framework OpenGLES -framework QuartzCore -framework Security -framework SystemConfiguration -framework UIKit -weak_framework AdSupport -weak_framework CoreTelephony -weak_framework StoreKit -ObjC -lCardIO -lCrittercism_v5_2_0 -lPods-AFNetworkActivityLogger -lPods-AFNetworking -lPods-CocoaLumberjack -lPods-Lockbox -lPods-Mantle -lPods-UIAlertView+Blocks -lPods-apptentive-ios -lc++ -framework AVFoundation -framework Accelerate -framework AssetsLibrary -framework AudioToolbox -framework CFNetwork -framework CoreData -framework CoreGraphics -framework CoreMedia -framework CoreText -framework CoreVideo -framework Foundation -framework GoogleAppIndexing -framework Leanplum -framework MobileCoreServices -framework OpenGLES -framework QuartzCore -framework Security -framework SystemConfiguration -framework UIKit -weak_framework AdSupport -weak_framework CoreTelephony -weak_framework StoreKit -fobjc-arc -fobjc-arc -fobjc-link-runtime -liconv -lc++ -framework OpenGLES -framework PassKit -framework CoreVideo -framework CoreImage -lUAirship-5.1.1 -framework MapKit -framework MessageUI -framework CoreTelephony -framework Accelerate -framework QuartzCore -licucore -lsqlite3 -lz -framework Security -framework CFNetwork -lPods /Users/ymedialabs/Documents/Projects/Staples/iphone/Tableaux/Library/Helpers/ThirdParty/AdobeMobileLibrary/AdobeMobileLibrary.a -framework MobileCoreServices -framework CoreMedia -framework AudioToolbox -framework AVFoundation -framework SystemConfiguration -framework CoreLocation -framework CoreGraphics -framework UIKit -framework Foundation -Xlinker -dependency_info -Xlinker /Users/ymedialabs/Library/Developer/Xcode/DerivedData/Tableaux-ebmgmudfgnxeywcrugwznpisqeaq/Build/Intermediates/Tableaux.build/PreProd-iphoneos/Tableaux.build/Objects-normal/arm64/Tableaux_dependency_info.dat -o /Users/ymedialabs/Library/Developer/Xcode/DerivedData/Tableaux-ebmgmudfgnxeywcrugwznpisqeaq/Build/Products/PreProd-iphoneos/Tableaux.app/Tableaux

ld: warning: ignoring file /Users/ymedialabs/Documents/Projects/Staples/iphone/Pods/Leanplum-iOS-SDK/Leanplum.framework/Leanplum, file was built for unsupported file format ( 0x2F 0x2F 0x0A 0x2F 0x2F 0x20 0x20 0x4C 0x65 0x61 0x6E 0x70 0x6C 0x75 0x6D 0x2E ) which is not the architecture being linked (arm64): /Users/ymedialabs/Documents/Projects/Staples/iphone/Pods/Leanplum-iOS-SDK/Leanplum.framework/Leanplum
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_Leanplum", referenced from:
      objc-class-ref in SCTagHelper.o
      objc-class-ref in STLibraryService.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

GenerateDSYMFile /Users/ymedialabs/Library/Developer/Xcode/DerivedData/Tableaux-ebmgmudfgnxeywcrugwznpisqeaq/Build/Products/PreProd-iphoneos/Tableaux.app.dSYM /Users/ymedialabs/Library/Developer/Xcode/DerivedData/Tableaux-ebmgmudfgnxeywcrugwznpisqeaq/Build/Products/PreProd-iphoneos/Tableaux.app/Tableaux
    cd /Users/ymedialabs/Documents/Projects/Staples/iphone
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/ymedialabs/Library/Developer/Xcode/DerivedData/Tableaux-ebmgmudfgnxeywcrugwznpisqeaq/Build/Products/PreProd-iphoneos/Tableaux.app/Tableaux -o /Users/ymedialabs/Library/Developer/Xcode/DerivedData/Tableaux-ebmgmudfgnxeywcrugwznpisqeaq/Build/Products/PreProd-iphoneos/Tableaux.app.dSYM

error: cannot parse the debug map for "/Users/ymedialabs/Library/Developer/Xcode/DerivedData/Tableaux-ebmgmudfgnxeywcrugwznpisqeaq/Build/Products/PreProd-iphoneos/Tableaux.app/Tableaux": No such file or directory

**Comment by paulb777** [comment]
Do you see the same problem with a non-beta Xcode and building for iOS 8.x? Or is it dependent upon the Xcode beta and building for iOS 9?

**Comment by karthikkeyan** [comment]
Actually i didn't try in non-beta XCode. I have El Capitan on my system, I can't run Xcode 6.4. I kind of stuck here. Basically i running the code from Xcode 7 Beta 3 to the device which have iOS 9 Beta 3.

**Comment by paulb777** [comment]
I'll investigate.

**Comment by paulb777** [comment]
I've reproduced the issue and I'm working on a fix. In the meantime, you can go back to 1.3.3 by editing the Podfile to:

pod 'Leanplum-iOS-SDK', '1.3.3'

and running pod update

**Comment by paulb777** [comment]
Fixed in 1.3.6.2. Run pod update.

The 1.3.6 Cocoapods installation was corrupted. The Leanplum 1.3.6 iOS SDK is correctly packaged in the 1.3.6.2 Cocoapods version.

**Comment by karthikkeyan** [comment]
Awesome. Thanks for the quick fix @paulb777
