### ISSUE TITLE
Are there static libraries contained within the LeanPlum framework?

### ISSUE THREAD

**Issue by n8tr** [Leanplum/Leanplum-iOS-SDK#4]
We are getting a CocoaPods error when trying to enable Swift code in our private pod that has a dependency on the LeanPlum framework.  This seems to point to Leanplum having internal static libraries, which cannot be used within a Swift enabled pod.  

[!] The 'Pods-MyPrivatePod' target has transitive dependencies that include static binaries: (/myPath/Pods/Leanplum-iOS-SDK/Leanplum.framework)

**Comment by benmarten** [comment]
We've updated the framework to a dynamic lib now. Please try the latest version. Thanks!
