### ISSUE TITLE
XCode14 property availability compilation fail

### ISSUE THREAD

**Issue by atsumori** [Leanplum/Leanplum-iOS-SDK#512]
With Xcode 14 Beta 5 library fails to compile with following error

Stored properties cannot be marked potentially unavailable with `@available`

<img width="500" alt="スクリーンショット 2022-08-23 23 05 50" src="https://user-images.githubusercontent.com/1137234/186179359-70174f3d-a30f-427b-9b04-01453752d80b.png">

**Comment by drupert-imvu** [comment]
I'm having this problem too using Xcode 14 beta 6.

**Comment by zumaawad** [comment]
I have the same issue with XCode version 14.0 (14A309)

![Screen Shot 2022-09-14 at 12 32 53 PM](https://user-images.githubusercontent.com/11634587/190131539-b05e47d7-ec5d-4c92-b0c4-ff5ac430ff9d.png)

**Comment by kishan-ck** [comment]
I have Same issue 

> I have the same issue with XCode version 14.0 (14A309)
> 
> ![Screen Shot 2022-09-14 at 12 32 53 PM](https://user-images.githubusercontent.com/11634587/190131539-b05e47d7-ec5d-4c92-b0c4-ff5ac430ff9d.png)

**Comment by jonameson** [comment]
We are having the same issue. Any workaround?

**Comment by drupert-imvu** [comment]
I was able to fix the problem for my project by changing the deployment target in the PodFile from iOS 8 to iOS 13. I chose 13 because that was the min version my app supports. I didn't investigate to see if it would work with other iOS versions.

 post_install do |installer|
   installer.generated_projects.each do |project|
     project.targets.each do |target|
         target.build_configurations.each do |config|
             if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
               config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
             end
          end
     end
   end
 end
