### ISSUE TITLE
Broken SPM support

### ISSUE THREAD

**Issue by vlad-shostak** [Leanplum/Leanplum-iOS-SDK#537]
## Expected Behavior
Build project and resolve dependencies using SPM.

## Actual Behavior
`Package.swift` contains errors and couldn't allow to resolve dependencies.

## Specifications
  - Version: 6.0.0

**Comment by nzagorchev** [comment]
Hi, the CI broke the Package.swift due to some non-updated script. 
Can you try using 6.0.1?

**Comment by vlad-shostak** [comment]
Hi, @nzagorchev. Now everything is ok. Thank you a lot🙌🏾

**Comment by nzagorchev** [comment]
Hi @vlad-shostak, sorry about that, and thanks for the feedback! Glad that it works now.

Fixed with #538 with 6.0.1.
