### ISSUE TITLE
LPWebInterstitial banner doesn't display

### ISSUE THREAD

**Issue by vlad-shostak** [Leanplum/Leanplum-iOS-SDK#539]
## Expected Behavior
`LPWebInterstitial` is visible.

## Actual Behavior
`LPWebInterstitial` isn't visible.

## Steps to Reproduce the Problem
Just put the banner on one of the application screens. On `Leanplum 4.1.0` it's visible but I can't interact with the underlying view controller. On `Leanplum 6.0.1` I don't see it.

## Specifications
  - Version: `Leanplum 6.0.1`
  - Platform: `iOS 16`

**Comment by nzagorchev** [comment]
@vlad-shostak can you provide a sample application? I am not able to reproduce it on our test apps.

**Comment by vlad-shostak** [comment]
@nzagorchev I think it'll a quite complicated:) was something changed in handling or creating LPWebInterstitial banners related to the `4.1.0` version?

**Comment by nzagorchev** [comment]
The change is in the presentation style:
[4.1.0](https://github.com/Leanplum/Leanplum-iOS-SDK/blob/4.1.0/LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/LPRichInterstitialMessageTemplate.m#L52):
`viewController.modalPresentationStyle = UIModalPresentationOverFullScreen;`
[6.0.1](https://github.com/Leanplum/Leanplum-iOS-SDK/blob/6.0.1/LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/LPRichInterstitialMessageTemplate.m#L63):
`viewController.modalPresentationStyle = UIModalPresentationOverCurrentContext;`

**Comment by nzagorchev** [comment]
@vlad-shostak Any update on how to reproduce or if you figured it out yourself based on the changes?

**Comment by vlad-shostak** [comment]
@nzagorchev sorry, couldn't back to task for some time. Could I ask you make a separate version with this changes? Due to the fact that you deliver a framework as a binary dependency it not easy to check the hypothesis.

**Comment by vlad-shostak** [comment]
@nzagorchev, could you set `definesPresentationContext` to `true` for a VC that is presented as `UIModalPresentationOverCurrentContext`.

**Comment by nzagorchev** [comment]
Hi @vlad-shostak ,
We were busy working on ReactNative and Unity SDKs, now I got the chance to look back into this, please excuse me for the delay.

I believe the presenting controller should have the context set in this case. Please, take a look into this branch with those changes:
https://github.com/Leanplum/Leanplum-iOS-SDK/tree/banner-context

Let me know more about your use case and if the above solves it.

**Comment by vlad-shostak** [comment]
Hi @nzagorchev,
Still nothing. Nothing special in our case. I tried to present this banner in different screens there're shown via push or present but result is the same.

**Comment by nzagorchev** [comment]
- Can you send me a sample application I can test with? 
- Or set the log level to Debug and trigger the message, so we can check the logs?
- Also, it is possible that the template file is corrupted - Can you delete the app and install it again in Prod mode?

Otherwise, I assume there is another controller or something else preventing the banner to show up.

**Comment by vlad-shostak** [comment]
@nzagorchev, yeah I enabled debug log level and saw this:
`2022-12-21 15:30:06.764803+0200 Vivid[7552:22298767] [LEANPLUM] [ERROR]: Error in message template HTML: Could not find a storyboard named 'WebInterstitial' in bundle NSBundle </Users/anduse/Library/Developer/CoreSimulator/Devices/04B795BA-8A4F-4EBB-B4F0-BF6A0B0B248C/data/Containers/Bundle/Application/654AB3B5-0042-4A31-AE72-D38D74457358/Vivid.app> (loaded)
(
	0   CoreFoundation                      0x0000000138b38304 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000132b6131c objc_exception_throw + 56
	2   UIKitCore                           0x0000000150098298 -[UIStoryboard name] + 0
	3   Vivid                               0x000000010c916844 +[LPWebInterstitialViewController instantiateFromStoryboard] + 64
	4   Vivid                               0x000000010c90e500 -[LPRichInterstitialMessageTemplate viewControllerWithContext:] + 36
	5   Vivid                               0x000000010c90e3bc __49+[LPRichInterstitialMessageTemplate defineAction]_block_invoke + 80
	6   Vivid                               0x000000010c94c5cc $sSo15LPActionContextC10ObjectiveC8ObjCBoolVIeyByd_ABSbIeggd_TRTA + 24
	7   Vivid                               0x000000010c948be8 $s8Leanplum13ActionManagerC14performActionsyyF + 2156
	8   Vivid                               0x000000010c948ec8 $s8Leanplum13ActionManagerC14performActionsyyFTo + 28
	9   Vivid                               0x000000010c9386f0 $sIeg_IeyB_TR + 28
	10  libdispatch.dylib                   0x000000013bb58594 _dispatch_call_block_and_release + 24
	11  libdispatch.dylib                   0x000000013bb59d5c _dispatch_client_callout + 16
	12  libdispatch.dylib                   0x000000013bb6a808 _dispatch_main_queue_drain + 1316
	13  libdispatch.dylib                   0x000000013bb6a2d4 _dispatch_main_queue_callback_4CF + 40
	14  CoreFoundation                      0x0000000138a9cb88 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
	15  CoreFoundation                      0x0000000138a97318 __CFRunLoopRun + 1956
	16  CoreFoundation                      0x0000000138a9675c CFRunLoopRunSpecific + 584
	17  GraphicsServices                    0x000000013d33bc98 GSEventRunModal + 160
	18  UIKitCore                           0x000000014ff4cb74 -[UIApplication _run] + 868
	19  UIKitCore                           0x000000014ff50b1c UIApplicationMain + 124
	20  Vivid                               0x0000000102844ed8 main + 612
	21  dyld                                0x000000012b371fa0 start_sim + 20
	22  ???                                 0x000000012b46908c 0x0 + 5021012108
	23  ???                                 0x0b7f800000000000 0x0 + 828521593947815936
)`

**Comment by nzagorchev** [comment]
It cannot find the storyboard from the Leanplum Bundle. This is why it cannot be presented.

Can you let me know how you have integrated Leanplum? We can start from there and see why it cannot find the bundle.

Generally, it is located under the Leanplum framework, for example:
`NSBundle </var/containers/Bundle/Application/63C848D5-A126-4131-A920-B44B51DA150D/Rondo-iOS.app/Frameworks/Leanplum.framework/Leanplum-iOS-SDK.bundle>`

**Comment by nzagorchev** [comment]
Hi @vlad-shostak,

Can you add the following Run Script Phase to the project:
`cp -R -L ${BUILT_PRODUCTS_DIR}/Leanplum.framework/*.bundle ${BUILT_PRODUCTS_DIR}/${TARGET_NAME}.app
`
This will copy over the bundle and resolve the issue.

**Comment by vlad-shostak** [comment]
Hi @nzagorchev,

It helped us🎉 thank you so much
