### ISSUE TITLE
Your dependency CleverTap is using old version of SDWebImage

### ISSUE THREAD

**Issue by mrazam110** [Leanplum/Leanplum-iOS-SDK#549]
## Expected Behavior
Should use the latest version of SDWebImage

## Actual Behavior
Leanplum's dependency CleverTap is using old version of SDWebImage

## Specifications

  - Version: 6.0.2
  - Platform: iOS
  - Subsystem:

Seems like someone already raised this [issue](https://github.com/CleverTap/clevertap-ios-sdk/issues/219) with them around 3 weeks ago

**Comment by nzagorchev** [comment]
Hi @mrazam110 
Do you use SDWebImage as a dependency for your app? Which version are you using?

Currently, Leanplum SDK is set for CleverTap versions up to 4.2.0 but not including it. We need to test the compatibility with the latest version in order to do a new release.

**Comment by mrazam110** [comment]
We use the most latest version of SDWebImage 5.14

**Comment by mrazam110** [comment]
CleverTap has updated the SDWebImage version on their podspec with their new version. Kindly update CleverTap version on Leanplum's podspec @nzagorchev

**Comment by nzagorchev** [comment]
Hi @mrazam110,
You can see the changes in the PR linked to this issue.
I have created a new beta version which is currently in QA.

**Comment by nzagorchev** [comment]
Released in 6.0.3
