### ISSUE TITLE
Button Action of InAppMessages deeplink not working

### ISSUE THREAD

**Issue by mrazam110** [Leanplum/Leanplum-iOS-SDK#558]
## Expected Behavior
Button Action should call deeplink

## Actual Behavior
Button Action is just dismissing the InAppMessageController not delivering another action
Its working fine with v4.1.0 but not with 6.0.3

## Steps to Reproduce the Problem

  1. 
![Screenshot 2023-02-20 at 11 20 47 AM](https://user-images.githubusercontent.com/5674070/220078422-66596e0d-757f-4fca-8cfc-7823f2f4e1c1.png)
Created message from leanplum portal

  2. It will be visible on the app
  3. Click on Add Credit Button
  4. Should take it to another screen

## Specifications

  - Version: 6.0.3
  - Platform: iOS
  - Subsystem:

**Comment by nzagorchev** [comment]
Hello,

I see that this is a custom action. Please, check the changelog regarding In-app messages and Actions in 5.0.0:
https://docs.leanplum.com/changelog/custom-in-app-templates-migration-ios-500

If the in-app leading to the action is also a custom one, please ensure you are calling `context.actionDismissed()` when dismissing the message.
