### ISSUE TITLE
Runtime issue after Leanplum.start()

### ISSUE THREAD

**Issue by AntonRomanchuk** [Leanplum/Leanplum-iOS-SDK#573]
## Problem
It is taking our app ~ 1 minute every time before start. From our findings we start the app and then nothing happens until a purple warning appears saying: 
```The request of a upload task should not contain a body or a body stream, use `upload(for:fromFile`, `upload(for:from`, or supply the body stream through the `urlSession(_:needNewBodyStreamForTask` delegate method.```

After the purple warning appears, our app continues its processes

## Expected Behavior
No purple warnings in a project from leanplum sdk

## Actual Behavior
When app is calling Leanplum.start() we got next runtime issue:
```The request of a upload task should not contain a body or a body stream, use `upload(for:fromFile`, `upload(for:from`, or supply the body stream through the `urlSession(_:needNewBodyStreamForTask` delegate method.```

## Steps to Reproduce the Problem

  1. Call Leanplum.start() at first screen of the app

## Specifications

  - Version: 6.1.1
  - Platform: iOS
  - Subsystem: iOS 16-17

**Comment by AntonRomanchuk** [comment]
Still reproducible on 6.2.0-beta2

**Comment by nzagorchev** [comment]
Can you check if it is fixed with 6.2.0? I am no longer able to reproduce this.

**Comment by AntonRomanchuk** [comment]
No longer reproducible, thanks!
