### ISSUE TITLE
didRegisterForPushNotification callback

### ISSUE THREAD

**Issue by rpassis** [Leanplum/Leanplum-iOS-SDK#59]
Not sure if here is the best place for raising this but the documentation for push notifications doesn’t mention anything about the `didRegisterForPushNotification` callback and how to send an acquired device token to your server. 

It turns out there’s a bit of swizzling magic happening in the background so the SDK seems to be taking care of it. 

In this case I think it is at least worthwhile mentioning it and documenting the expected behaviour. 

From my tests the framework captures that callback,
saved the token and then relays the message to the original app delegate method. 

Is this correct?

Cheers
Rog

**Comment by milos1290** [comment]
Yes, you are correct, we are using method swizzling to intercept method call and send the token back to our servers. This way we provide easier setup of our SDK.

**Comment by benmarten** [comment]
@mattleanplum Hi Matt, maybe we can add this to our docs?

**Comment by benmarten** [comment]
This is where the app delegate method gets swizzled: https://github.com/Leanplum/Leanplum-iOS-SDK/blob/develop/Leanplum-SDK/Classes/LPActionManager.m#L94
and here is our implementation: https://github.com/Leanplum/Leanplum-iOS-SDK/blob/develop/Leanplum-SDK/Classes/LPActionManager.m#L64
