### ISSUE TITLE
No way to defer location permissions prompts

### ISSUE THREAD

**Issue by n00neimp0rtant** [Leanplum/Leanplum-iOS-SDK#6]
_This issue only manifests when linking against one of the supplementary location/beacon libraries._

Correct me if I'm wrong, but it doesn't look like there's any supported way to tell Leanplum that it should never present a prompt asking for user's location. When linking against the location or beacon library, the app prompts the user on launch, which is annoying for users and greatly reduces overall opt-in (some light reading on the subject: http://techcrunch.com/2014/04/04/the-right-way-to-ask-users-for-ios-permissions/ ). Our app contains complex logic so that location permission prompts are shown at just the right time to maximize user opt-in, but Leanplum aggressively presents it as soon as `[Leanplum start]` is called.

For now, I'm swizzling CLLocationManager and NOPing all authorization requests made by Leanplum, but this is far from ideal.

**Comment by afirst** [comment]
Hi, thanks for the suggestion! That is the best workaround for now. We'll incorporate this option in the next release.

**Comment by gigasmile** [comment]
Closing old open issues.
Note you can set authorizeAutomatically to false in LPLocationManager to handle this.
