### ISSUE TITLE
compilation error w/ latest sdk: 1.4.0

### ISSUE THREAD

**Issue by jaz-ah** [Leanplum/Leanplum-iOS-SDK#8]
occurs with Xcode7.3.1 and Xcode8 Beta6, both when installing from cocoapods.

![screen shot 2016-09-07 at 8 57 34 am](https://cloud.githubusercontent.com/assets/13263369/18319103/34109f40-74d9-11e6-92fc-4041130340a0.png)

**Comment by benmarten** [comment]
Thanks for reporting this. That was a glitch in our packaging script. I've corrected the header file.

Running `pod install` should resolve the issue.

You might have to clear your cocoapods cache if it doesn't work right away:
```
rm -rf ~/Library/Caches/CocoaPods/Pods/Release/Leanplum-iOS-SDK/
rm -rf ~/Library/Caches/CocoaPods/Pods/Specs/Release/Leanplum-iOS-SDK/
rm -rf <PROJECT_DIR>/Pods/Leanplum-iOS-SDK/
pod install
```

Let me know if that works for you!

**Comment by jaz-ah** [comment]
works ok now  -thanks!
