### ISSUE TITLE
Carthage Binary Specification

### ISSUE THREAD

**Issue by justin** [Leanplum/Leanplum-iOS-SDK#80]
Hi,

Carthage added support for a [new binary specification format](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification) in a recent release that I believe would make everyone's lives easier (at last those of us who are unable to use Pods). 

On your end I believe it would just require you to update a JSON file either in this GitHub repo with a new new line for each release pointing to the zip file of the binary download.

I have an example of a Leanplum spec file on my fork: https://github.com/justin/Leanplum-iOS-SDK/blob/feature/carthage-spec/Leanplum-iOS-SDK.json

The benefit for us as consumers of your framework that we can specify in our Cartfile that we are wanting to fetch a binary framework, thus running `carthage update` or `carthage bootstrap` with a specific Swift toolchain won't fail because it doesn't know how to build Leanplum.

Example:

```
binary "https://raw.githubusercontent.com/justin/Leanplum-iOS-SDK/feature/carthage-spec/Leanplum-iOS-SDK.json" ~> 2.0.
```

It'd be great if you all could consider and implement this on your end. Thanks!

**Comment by alexisoyama** [comment]
Other customer have also asked for this. We can definitely have a json file that have these specifications. Will mention it to our team.

**Comment by rpassis** [comment]
Hey @justin I'm pretty sure that if you run carthage update or bootstrap right now you will get the binary that is associated with the release tag you're asking for. 

Here's the (redacted) output of me running `carthage update Leanplum-iOS-SDK --platform ios`

> *** Downloading Leanplum-iOS-SDK.framework binary at "Leanplum iOS SDK 2.0.2"

My Cartfile just specifies the source and Carthage takes care of the rest.
`github "Leanplum/Leanplum-iOS-SDK" ~> 2.0.2`

(I think) the new binary specification use case is for private frameworks or other version control platforms that don't support downloads attached to releases (i.e. Bitbucket).

**Comment by justin** [comment]
Hey,

That does work usually. The problem we run into with it is when we specify the --toolchain option as part of our Carthage bootstrapping / updating purpose (for defining what swift version we want to build with for instance). When you use that, it seems like Carthage fails to handle binary frameworks using the 'github' DSL. 

We're on Swift 4 now, so this is less of an issue than when I reported it, but until Swift ABI goes stable (if it ever does), it's likely a recurring issue.

**Comment by alexisoyama** [comment]
It seems like there is a workaround and Swift 4 handles it better. Closing this for now. Please reopen if it is still an issue.
