### ISSUE TITLE
LPVar onValueChanged called on background thread

### ISSUE THREAD

**Issue by rpassis** [Leanplum/Leanplum-iOS-SDK#99]
Hi all,

I'm seeing instances where LPVar's `onValueChanged` is called on a background thread, is this expected behaviour? 

If so it would be great to have it documented somewhere since the setup instructions on this link [1]https://www.leanplum.com/docs/ios/callbacks#on-variables-changed indicate that it is safe to update the UI inside the valueChanged block but UIKit is NOT thread safe.

Thanks!
Rog

**Comment by alexisoyama** [comment]
Thanks for reporting. CSM and TSE will contact you shortly. That is not a desired behavior and we will fix it once we confirm the bug.

**Comment by rpassis** [comment]
<img width="1217" alt="screen shot 2017-12-20 at 3 42 10 pm" src="https://user-images.githubusercontent.com/387079/34191624-8b30d436-e59c-11e7-8485-5fc97d184e28.png">

Managed to catch this issue again today and thought I'd share a screenshot of our stack trace here.
You can see that the callback is getting triggered on Thread 24 via `[Leanplum triggerStartResponse:]`.

It doesn't happen consistently but it's definitely there. I'll see if I can find a way to reliably reproduce it.

**Comment by alexisoyama** [comment]
I think I know why this one is happening. Will have a fix for this. 
Will also add extra protection for onValueChanged.

**Comment by alexisoyama** [comment]
Fixed by https://github.com/Leanplum/Leanplum-iOS-SDK/pull/116. Released in 2.0.5
